### PR TITLE
Explicitly link MLIRMemRefTransforms library

### PR DESCRIPTION
**Pull request by adam-smnk**
Fixes symbol issues during linking.

### CODE REVIEW

**Comment by rengolin** [comment]
> Fixes symbol issues during linking.

Which issues?

**Comment by adam-smnk** [comment]
Locally I get:
```
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
lib/libTPPGPU.a(GpuToVulkan.cpp.o): in function `(anonymous namespace)::GpuToVulkan::constructPipeline()':
GpuToVulkan.cpp:(.text._ZN12_GLOBAL__N_111GpuToVulkan17constructPipelineEv+0x25): undefined reference to `mlir::memref::createFoldMemRefAliasOpsPass()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rengolin** [comment]
> Locally I get:

How did this pass CI?

**Comment by adam-smnk** [comment]
> > Locally I get:
> 
> How did this pass CI?

Ohhh now I see, I was linking using `ld` instead of `lld` which is used by CI.

**Comment by adam-smnk** [comment]
It probably doesn't hurt to have this lib linked anyway.

**Review by rengolin — APPROVED** [review]
Indeed, relying on compiler/linker behaviour is not stable.

**Pull request merged**
