### PR TITLE
Do not interchange in `packVNNIMatmulOp`

### PR DESCRIPTION
**Pull request by chelini**
- Packing introduces an interchange on the packed dimension; there is no
  obvious reason for doing this, and it breaks the "canonical" form. If we
  need to introduce an interchnage, we need to do this explicitly and not
  while packing.

- Make sure we can handle possible interchanges when mapping to BRGEMM.
  See changes in `isBrgemmVnniOp`.

### CODE REVIEW

**Comment by adam-smnk** [comment]
Any impact on benchmarks?

**Comment by chelini** [comment]
> Any impact on benchmarks?

Currently, tests are timed out as we need to match what MLIR-gen generates. During packing, we moved the VNNI dimension. We pack as [p, p, r, r, p, p, r] instead of [p, p, r, p, p, r, r]. MLIR-gen copied the behavior, @KavithaTipturMadhu . Do you remember why we pack this way?

Possible solutions:
1. Adjust mlir-gen
2. Improve detection `isVnniBrgemmOp` to cover also possible interchange happening during packing

**Comment by KavithaTipturMadhu** [comment]
> > Any impact on benchmarks?
> 
> Currently, tests are timed out as we need to match what MLIR-gen generates. During packing, we interchange the VNNI dimension. We pack as [p, p, r, r, p, p, r] instead of [p, p, r, p, p, r, r]. MLIR-gen copied the behavior, @KavithaTipturMadhu . Do you remember why we pack this way?
> 
> Possible solutions:
> 
> 1. Adjust mlir-gen
> 2. Improve detection `isBrgemmVnniOp` to cover also possible interchange happening during packing. The current form: https://github.com/plaidml/tpp-mlir/blob/dc64f73abb679b1f6d6333acf9764d4d8e898ec6/lib/TPP/Dialect/Tpp/TppUtils.cpp#L30
>     expects a specific iterator order.
> 
> We should generally not care about possible interchanges, so extending the matcher should be done anyway. But I feel we should not interchange during packing if there are no good reasons for doing that.

I don't recall exactly why I chose to pack as [p, p, r, r, p, p, r], sorry. It should've been [p, p, r, p, p, r, r] as you pointed out.

**Comment by chelini** [comment]
> > > Any impact on benchmarks?
> > 
> > 
> > Currently, tests are timed out as we need to match what MLIR-gen generates. During packing, we interchange the VNNI dimension. We pack as [p, p, r, r, p, p, r] instead of [p, p, r, p, p, r, r]. MLIR-gen copied the behavior, @KavithaTipturMadhu . Do you remember why we pack this way?
> > Possible solutions:
> > 
> > 1. Adjust mlir-gen
> > 2. Improve detection `isBrgemmVnniOp` to cover also possible interchange happening during packing. The current form: https://github.com/plaidml/tpp-mlir/blob/dc64f73abb679b1f6d6333acf9764d4d8e898ec6/lib/TPP/Dialect/Tpp/TppUtils.cpp#L30
> >    
> >    expects a specific iterator order.
> > 
> > We should generally not care about possible interchanges, so extending the matcher should be done anyway. But I feel we should not interchange during packing if there are no good reasons for doing that.
> 
> I don't recall exactly why I chose to pack as [p, p, r, r, p, p, r], sorry. It should've been [p, p, r, p, p, r, r] as you pointed out.

Ok thanks, np. This should be ok now.

**Pull request merged**
