### PR TITLE
Issue #669: updated CUDA API to v12.2

### PR DESCRIPTION
**Pull request by hfp**

### CODE REVIEW

**Review by rengolin — CHANGES_REQUESTED** [review]
This will change the LLVM version without fixing the delta and will break the build.

If the cluster is ready to take on the 12.2 change, then this should be done in #665 directly.

**Comment by hfp** [comment]
On the other hand, basic tests like building `tpp-mlir` are failing with the new LLVM version hence I think #665 must go first.

**Comment by adam-smnk** [comment]
It seems that after changing the CUDA version, the sanitizer kicks in when it should be disabled for the GPU tests.
`tpp-gpu` is optional so #665 could be merged to move things forward and I can investigate this CI failure separately.

**Comment by rengolin** [comment]
> On the other hand, basic tests like building `tpp-mlir` are failing with the new LLVM version hence I think #665 must go first.

Not first, together. This change in #665 would probably fix the test, which is what we want. We don't need two different PRs.

**Comment by hfp** [comment]
> > On the other hand, basic tests like building `tpp-mlir` are failing with the new LLVM version hence I think #665 must go first.
> 
> Not first, together. This change in #665 would probably fix the test, which is what we want. We don't need two different PRs.

Never mind. I can pull @chelini 's draft-PR into this PR.

**Comment by hfp** [comment]
> It seems that after changing the CUDA version, the sanitizer kicks in when it should be disabled for the GPU tests. `tpp-gpu` is optional so #665 could be merged to move things forward and I can investigate this CI failure separately.

@adam-smnk Now, only the ASAN issue seems to be leftover.

**Comment by adam-smnk** [comment]
CUDA not cooperating with asan is nothing new. But it seems that sth is even more broken in the newest drivers with CUDA 12+ as mentioned [here](https://github.com/google/sanitizers/issues/1630).
For now, simply disabling sanitizers in CUDA CI might be the only way forward.

**Review by rengolin — APPROVED** [review]

**Pull request merged**
