### PR TITLE
Fix benchmarks flops

### PR DESCRIPTION
**Pull request by adam-smnk**
Fixes tensor sizes and flops calculations in a benchmark kernels.

### CODE REVIEW

**Review by chelini — APPROVED** [review]

**Comment by rengolin** [comment]
hmm
image

**Comment by adam-smnk** [comment]
MLP base kernel sizes were fine but the total numbers of flops were incorrect.

**Comment by adam-smnk** [comment]
image
Small drop in unpacked gemm performance as I reenabled packing. It doesn't particularly change overall test runtime but it was the only remaining test case with packing explicitly disabled. Thus, it is better to just run the default pipeline without extra options.

image
image
After the mlp flops fix, the two gemm and mlp kernels, using the same tensor sizes and both prepacked, achieve similar performance.

**Review by rengolin — APPROVED** [review]
Stupid copy pasta! :face_exhaling:

**Pull request merged**
