### PR TITLE
Retire pack of reshape

### PR DESCRIPTION
**Pull request by adam-smnk**
Replaces downstream pass with upstreamed data layout propagation pattern.

### CODE REVIEW

**Comment by adam-smnk** [comment]
Depends on #931

**Comment by adam-smnk** [comment]
No benchmark regressions.

**Comment by rengolin** [comment]
Is the gpu flag change just a factor from the llvm bump?

**Comment by adam-smnk** [comment]
> Is the gpu flag change just a factor from the llvm bump?

Yes, for this change you need to look into the newer commit separately.
I guess stacking PRs still sucks on github :/

**Review by rengolin — APPROVED** [review]

**Pull request merged**
