### PR TITLE
Adds OpenMP benchmarks

### PR DESCRIPTION
**Pull request by rengolin**
Reuse existing MLIR files to run benchmarks with OpenMP options.

Adds `environment` setting to the driver.

### CODE REVIEW

**Comment by adam-smnk** [comment]
Infrastructure looks fine but I'm a bit puzzled the performance numbers.
Also, when I run the `openmp` benchmarks locally, I see only a single thread being occupied.

**Comment by rengolin** [comment]
> Infrastructure looks fine but I'm a bit puzzled the performance numbers. Also, when I run the `openmp` benchmarks locally, I see only a single thread being occupied.

Yes, @KavithaTipturMadhu nailed it: we always use `taskset`. I'm addressing this now.

**Comment by rengolin** [comment]
More reasonable results now:
| Bench | Single | 4 | 8 | 16 |
| --- | --- | --- | --- | --- |
| GEMM FP32 3x1024 | 80.794 | 294.331 | 484.523 | 733.424 |
| MLP FP32 3x1024 | 52.631 | 195.332 | 336.061 | 479.477 |

Still _not great_ but scaling up at least.

**Review by adam-smnk — APPROVED** [review]

**Comment by adam-smnk** [comment]
That deviation `gemm_fp32_3x1024_omp_16_mlir:   733.424 +-   248.724 gflops`  👀

**Pull request merged**
