### PR TITLE
Add simple heuristic to tile large m and n dimensions

### PR DESCRIPTION
**Pull request by chelini**
Locally, I see improvement for the MHA with sequence len 1024: 24,886 GFLOP/s to 31,175 GFLOP/s (single thread).

### CODE REVIEW

**Comment by adam-smnk** [comment]
> Locally, I see improvement for the MHA with sequence len 1024: 24,886 GFLOP/s to 31,175 GFLOP/s (single thread).

Changes look fine but I see some regression in longer MHA tpp-bench: [PR](https://buildkite.com/intel/tpp-benchmark/builds/1196#018a8928-9d62-4a20-a00c-812730a1e759) vs [main](https://buildkite.com/intel/tpp-benchmark/builds/1194#018a88e8-e681-49a0-8c3c-a1eabe77c6ef)

**Review by adam-smnk — APPROVED** [review]
LGTM, just please double check the performance numbers.

**Comment by chelini** [comment]
> LGTM, just please double check the performance numbers.

Interesting I see completely the opposite locally. Let me try to investigate.

**Comment by adam-smnk** [comment]
> Interesting I see completely the opposite locally. Let me try to investigate.

I reran the bench on a [separate PR](https://buildkite.com/intel/tpp-benchmark/builds/1197#018a895c-c59c-44e2-8c71-712de2bfd99d) and the result is in between the two numbers I linked before:
`fp32_mha_tensorflow_seq_len_1024:    32.948`

Looks like this is some natural deviation in the measurements.

**Pull request merged**
