### PR TITLE
Bump LLVM

### PR DESCRIPTION
**Pull request by chelini**
- Upstream changes for AggregateOp interface

- Better bufferization for eltwise

### CODE REVIEW

**Comment by hfp** [comment]
The new LLVM build now passes with CUDA v12.2. However, `tpp-mlir` fails like https://buildkite.com/intel/tpp-mlir/builds/2756#0189f8a0-b68c-4139-b23c-8dc5ebd37bec/130-329.

**Comment by chelini** [comment]
> The new LLVM build now passes with CUDA v12.2. However, `tpp-mlir` now fails like https://buildkite.com/intel/tpp-mlir/builds/2756#0189f8a0-b68c-4139-b23c-8dc5ebd37bec/130-329.

Ok thanks a lot. I will take care.

**Comment by hfp** [comment]
Sorry, I rebased the branch already as we talked based on GitHub's Web interface.

**Comment by hfp** [comment]
> Sorry, I rebased the branch already as we talked based on GitHub's Web interface.

... and it passes now: https://buildkite.com/intel/tpp-mlir/builds/2757

**Comment by hfp** [comment]
This PR was folded into #670.

**Pull request closed without merging**
